### ISSUE TITLE
[Suggestion] Cookbook should check sshd_config syntax before restart the service

### ISSUE THREAD

**Issue by chrisduong** [opscode-cookbooks/openssh#59]
Hi,

I think it is very useful that we only  restart the `sshd` service only if the syntax is correct by running the simple command to check.

```bash
sshd -t
```

By this way, we cannot be locked out of the server.

**Comment by jtimberman** [comment]
We should do this with the `verify` property on the template resource for the sshd config.

**Comment by tas50** [comment]
This issue bit me and I'm planning to spend some tim next week getting the fix out

**Comment by chrisduong** [comment]
Thanks for the feedback :)

**Comment by tas50** [comment]
This change is out in the 1.5.0 release
