### ISSUE TITLE
Ubuntu 15 fails because /sbin/status is not found

### ISSUE THREAD

**Issue by Paladin** [opscode-cookbooks/openssh#60]
Not sure if this is rightly here or in chef's Upstart code, but using

$> chef -v
Chef Development Kit Version: 0.6.0
chef-client version: 12.3.0
berks version: 3.2.4
ckitchen version: 1.4.0

and openssh cookbook 1.4.0

to build ubuntu 15.04 server I get an error:

         * service[ssh] action enable
       
           ================================================================================
           Error executing action `enable` on resource 'service[ssh]'
           ================================================================================
           
           Errno::ENOENT
           -------------
           No such file or directory - /sbin/status
           
None of those files (enable, restart, status) exist in /sbin in the 15.04 image I'm building from. The same cookbook in the same environment builds 14.04 just fine. (and while there is no /sbin/status the command "service ssh status" works.

**Comment by Paladin** [comment]
A follow up with some more information. Falling back to version 1.3.0 of this cookbook seems to work well in Ubuntu 15 (can log in and the config file is correct) as well as Ubuntu 14.

**Comment by adepue** [comment]
@Paladin This should be resolved here:
https://github.com/opscode-cookbooks/openssh/pull/62

**Comment by tas50** [comment]
This should be fixed in the 1.5.0 release

**Comment by dmigous** [comment]
Same issue systemd/upstart change at debian:stretch.

**Comment by dmigous** [comment]
I think adding smth like

```
if  'debian' == node['platform']
  if Chef::VersionConstraint.new('>= 9').include?(node['platform_version'])
    service_provider = Chef::Provider::Service::Upstart
  else
    service_provider = Chef::Provider::Service::Systemd
  end
end
```

here: https://github.com/adepue/openssh/blob/ee32e90bc66d94a22b0ff82814e49d8d1b3d931e/recipes/default.rb#L69

will resolve issue
