### ISSUE TITLE
Can you release new version of the cookbook to the supermarket?

### ISSUE THREAD

**Issue by Kasen** [opscode-cookbooks/openssh#64]
@tas50. The fix provided by @viktorradnai is very important for us. Now cookbook doesn't work on centos 5.11. Can you release new version of cookbook to supermarket with this fix?

**Comment by tas50** [comment]
Sorry for the breaking change there.  It all worked in KitchenCI, but I think that had a complete path set.  The new version is out on supermarket. https://supermarket.chef.io/cookbooks/openssh#changelog
